{{ config(materialized='view') }}

SELECT
    TRIM(CONTAINER_ID) AS CONTAINER_ID,
    TIMESTAMP,
    ROUND(TEMPERATURE, 2) AS TEMPERATURE,
    ROUND(HUMIDITY, 2) AS HUMIDITY,
    ROUND(VIBRATION, 2) AS VIBRATION,
    UPPER(TRIM(STATUS)) AS STATUS,
    DATA_VALID
FROM ATMOSYNC_DB.RAW.SENSOR_DATA
WHERE CONTAINER_ID IS NOT NULL
  AND TIMESTAMP IS NOT NULL
  AND DATA_VALID = TRUE