{{ config(materialized='view') }}

SELECT
    CONTAINER_ID,
    TIMESTAMP,
    TEMPERATURE,
    HUMIDITY,
    VIBRATION,
    STATUS,
    DATA_VALID
FROM ATMOSYNC_DB.RAW.SENSOR_DATA
WHERE CONTAINER_ID IS NOT NULL
  AND TIMESTAMP IS NOT NULL