{{ config(materialized='view') }}

SELECT
    TRIM(COMMODITY) AS COMMODITY,
    TRIM(ORIGIN_MARKET) AS ORIGIN_MARKET,
    TRIM(SECONDARY_MARKET) AS SECONDARY_MARKET,
    ROUND(ORIGIN_PRICE_PER_KG, 2) AS ORIGIN_PRICE_PER_KG,
    ROUND(SECONDARY_MARKET_PRICE_PER_KG, 2) AS SECONDARY_MARKET_PRICE_PER_KG
FROM {{ ref('commodity_prices') }}
WHERE COMMODITY IS NOT NULL
  AND ORIGIN_MARKET IS NOT NULL
  AND SECONDARY_MARKET IS NOT NULL